---
title: "Syllabus Sociology of Conspiracy Theories"
format: html
editor: visual
embed-resources: true
---

Seminar ID: [30228](#0)\
Module: M8 / M5\
Lecturer: Philipp Wunderlich\
Contact: [philipp.wunderlich\@fu-berlin.de](#0)\
Time: Thursdays 14:00 - 16:00\
Room: Garystr.55/301\
Blackboard: [POLSOZ_V\_30228_23S](#0)\
Office hours: <https://calendly.com/philippwunderlich/office-hours>

# Course Description

Conspiracy theories are ubiquitous and have recently gained attention in new-right political campaigns, social media networks and in relation to the coronavirus pandemic. Nevertheless, sociology has its difficulties in defining and coming to terms with the phenomenon. This may in part be the case, because social theory and conspiracy theories both attempt to explain social phenomena and it can be hard to draw a demarcation line between the two (Nefes and Romero-Reche 2020). Also, the term itself is normatively charged and can be used strategically to discredit particular groups or actors. Last, knowledge of about the truth value of conspiracy theories is sometimes hard to come by. They often form hermetic imaginaries and belief systems that are hard to challenge and some of their claims may very well be factual.

In this course, we will draw on literature and analyses from a variety of disciplines in order to build a sociological understanding of conspiracy theories. This includes accounts from sociology of knowledge, sociology of emotions, social psychology, political sciences, media and communications studies and social theory, among others. The course goals are to 1.) arrive at a preliminary definition of conspiracy theories, 2.) understand micro- and macro-level conditions and mechanisms contributing to their emergence and dissemination through social networks and media channels 3.) gather field-specific knowledge on empirical cases, 4.) discuss practical approaches to decrease negative outcomes like societal polarization and extremism and 5.) critically discuss how conspiracy theories are socially constructed as a form of deviant knowledge and to which degree they may in some cases even increase agency and contribute to social change.

# Requirements

Regular participation credit

-   Attend all class meetings.

-   Complete the mandatory readings before each session.

Active participation credit

-   Active participation in class discussions

-   Complete the tasks listed in the course outline.

## Seminar Sessions

Seminar sessions are hold weekly and in presence on campus. It is mandatory to attend the sessions.

Importantly, make sure to *read the mandatory readings* before class and *take notes* on the reading. Readings are part of your regular participation requirements and are necessary to complete the active participation tasks.

## Presentation

Each participant has to prepare a short input presentation (10 minutes, possibly in groups).

## Writing tasks

-   One essay of min. 750 words is to be submitted mid-term

-   Students who don't need a module exam (i.e. Module 8 students who opt against an exam) need to submit a second essay of 750 words two weeks after the last class.

-   Students who need to complete a module exam (graded or ungraded) have to submit a seminar paper proposal two weeks after the last class session and have to hand in their seminar paper of 3.000 words at the end of the semester.

## Seminar Paper

You need to submit a term paper (Pass/Fail) in one of your two M8 Area of Specialization seminars, or a graded term paper if you take the seminar in Module 5.

For this seminar, term papers need to be uploaded as a Blackboard Assignment (PDF-format **and** MS Word / Open Office) by March 30, 2023.

The paper can be theoretical or empirical, should discuss one of the course's topics by developing an original research question, a plausible and theoretically well-grounded hypothesis, and a strong line of argument. The paper should take into account discussions in class and the relevant literature well beyond what is documented in the syllabus. Papers need to comprise 3.000 words.

We will go into more detail on how to structure a seminar paper and which aspects are relevant for your grade in the last session of the course.

## Missing Classes or Assignments

As per FU regulation you may miss up to 2 seminar sessions without a doctor's note. Missing more than 2 classes, will result in failing the regular participation requirement unless a doctor's note in presented.

Active participation credit will not be granted if you miss more than 2 reading response deadlines.

## Academic Integrity

This course is based on the principles of [academic integrity](https://www.fu-berlin.de/en/sites/gwp/informationen/satzung/index.html) established by Freie Universität Berlin. Academic dishonesty will not be tolerated. All documents submitted must be your own work and sources must be properly cited\

{{< pagebreak >}}

# Course Outline

Mandatory readings are marked with a star.

Many of the course readings are chapters taken from the following handbook:

Butter, M., & Knight, P. (Eds.). (2020). Routledge Handbook of Conspiracy Theories. Routledge. <https://doi.org/10.4324/9780429452734>

## Introduction

### 1) Introduction (2022-10-17)

-   Introduction to the topic.

    -   What are conspiracy theories?

    -   Why are they relevant?

-   Syllabus

-   Requirements

## Approaches to researching conspiracy theories

In the following four sessions, basic theoretical or empirical approaches to studying conspiracy theories will be revisited.

Each session will start with input from the lecturer and a class discussion, followed by some individual or group tasks. It is necessary to read the basic texts to be able to complete the class tasks successfully. As this is a writing-focused seminar, the first four sessions are supposed to lay the groundwork for individual essays that are to be entered in the following.

### 2) Traditional Accounts (2021-10-24)

Reading:

Hofstadter, R. (1996). *The paranoid style in American politics, and other essays* (1st Harvard University Press pbk. ed). Harvard University Press. <https://faculty.washington.edu/jwilker/353/Hofstadter.pdf>

Tasks:

### 3) Micro-level: Psychological Motives (2022-10-31)

Douglas, K. M., Cichocka, A., & Sutton, R. M. (2020). Motivations, Emotions and Belief in Conspiracy Theories. In *Routledge Handbook of Conspiracy Theories*. Routledge.

### 4) Macro-level: Structural predictors 2022-11-14

Smallpage, S. M., Drochon, H., Uscinski, J. E., & Klofstad, C. (2020). Who are the Conspiracy Theorists?: Demographics and conspiracy theories. In Routledge Handbook of Conspiracy Theories. Routledge.

### 5) Cultural perspectives: Identification and labelling (date)

Husting, G., & Orr, M. (2007). Dangerous Machinery: "Conspiracy Theorist" as a Transpersonal Strategy of Exclusion. Symbolic Interaction, 30(2), 127--150. <https://doi.org/10.1525/si.2007.30.2.127>

additional: Harambam, J., & Aupers, S. (2017). 'I Am Not a Conspiracy Theorist': Relational Identifications in the Dutch Conspiracy Milieu. Cultural Sociology, 11(1), 113--129. <https://doi.org/10.1177/1749975516661959>

Tasks:

-   Outline a 750 words theory essay (in TNR, double-spaced) for one of the given questions.

-   \@home complete the essay **until next session** for peer-review.

***Post 750 words essay to discussion forum***

## Collaborative Writing practice

### 6) Feedback & writing practice

-   Get together in groups of 3-4 and read each other's essays.

    -   Provide structured feedback to each other.

-   TASK two weeks to incorporate the feedback and upload finalized essays to the discussion forum.

## Studies and applications

In the following 5 sessions, we will cover specific empirical cases and theoretical issues relevant to the sociological research of conspiracy theories.

In each of these sessions, students will briefly present individual studies and contributions in short input presentations of 10 minutes length. After this there will be time to address comprehension questions and discuss the studies.

One goal of this block of sessions is to map out the field of research and collect ideas for final seminar papers / essays. Students are only required to read the text that they are presenting. Those who are not presenting in a given session are asked to chose one text and upload a comment or discussion questions pertaining to this text into the discussion forum.

### 7) Session 7: Alt-right conspiracy theories / Antisemitism

-   The alt-right and QAnon

    -   DiMaggio, A. R. (2022). Conspiracy Theories and the Manufacture of Dissent: QAnon, the 'Big Lie', Covid-19, and the Rise of Rightwing Propaganda. Critical Sociology, 48(6), 1025--1048. <https://doi.org/10.1177/08969205211073669>

    -   Bleakley, P. (2021). Panic, pizza and mainstreaming the alt-right: A social media analysis of Pizzagate and the rise of the QAnon conspiracy. Current Sociology, 00113921211034896. <https://doi.org/10.1177/00113921211034896>

-   Antisemitism

    -   Allington, D., & Joshi, T. (2020). "What Others Dare Not Say": An Antisemitic Conspiracy Fantasy and Its YouTube Audience. Journal of Contemporary Antisemitism, 3(1), 35--54. <https://doi.org/10.26613/jca/3.1.42>

    -   Simonsen, K. B. (2020). Antisemitism and Conspiracism. In M. Butter & P. Knight (Eds.), Routledge Handbook of Conspiracy Theories (pp. 357--370). Routledge. <https://doi.org/10.4324/9780429452734>

### 8) Session 8: Conspiracy theories in authoritarian regimes

-   Goertzel, T. (1994). Belief in Conspiracy Theories. Political Psychology, 15, 731--742. <https://doi.org/10.2307/3791630>

-   Turkish case:

    -   Nefes, T. S. (2017). The impacts of the Turkish government's conspiratorial framing of the Gezi Park protests. Social Movement Studies, 16(5), 610--622. <https://doi.org/10.1080/14742837.2017.1319269>

-   Post-soviet cases:

    -   Ortmann, S., & Heathershaw, J. (2012). Conspiracy Theories in the Post-Soviet Space. The Russian Review, 71(4), 551--564. https://doi.org/10.1111/j.1467-9434.2012.00668.x

    -   Yablokov, I. (2020). Conspiracy theories in Putin's russia---The case of the 'new World order.' In M. Butter & P. Knight (Eds.), Routledge Handbook of Conspiracy Theories (pp. 582--595). Routledge. <https://doi.org/10.4324/9780429452734>

***Submit revised 750 words essay***

### 9) Session 9: Post-truth and Counter-knowledge

-   Modernity and post-truth (Das gehört eventuell eher zu den Intro sessions)

    -   Lewandowsky, S., Ecker, U. K. H., & Cook, J. (2017). Beyond misinformation: Understanding and coping with the "post-truth" era. Journal of Applied Research in Memory and Cognition, 6(4), 353--369. <https://doi.org/10.1016/j.jarmac.2017.07.008>

    -   Aupers, S. (2012). 'Trust no one': Modernization, paranoia and conspiracy culture. European Journal of Communication, 27(1), 22--34. <https://doi.org/10.1177/0267323111433566>

-   Counter knowledge

    -   Gosa, T. L. (2011). Counterknowledge, racial paranoia, and the cultic milieu: Decoding hip hop conspiracy theory. Poetics, 39(3), 187--204. <https://doi.org/10.1016/j.poetic.2011.03.003>

### 10) Session 10: Gender and Sexuality / Political Ideology

-   Political ideology and populism:

    -   van der Linden, S., Panagopoulos, C., Azevedo, F., & Jost, J. T. (2021). The Paranoid Style in American Politics Revisited: An Ideological Asymmetry in Conspiratorial Thinking. Political Psychology, 42(1), 23--51. <https://doi.org/10.1111/pops.12681>

    -   Bergmann, E., & Butter, M. (2020). Conspiracy theory and populism. In M. Butter & P. Knight (Eds.), Routledge Handbook of Conspiracy Theories (pp. 292--303). Routledge. <https://doi.org/10.4324/9780429452734>

-   Gender and sexuality

    -   (+) Goetz, J. (2021). 'The Great Replacement' -- Reproduction and population policies of the far right, taking the Identitarians as an example. 16.

    -   Thiem, A. (2020). Conspiracy theories and gender and sexuality. In M. Butter & P. Knight (Eds.), Routledge Handbook of Conspiracy Theories (pp. 292--303). Routledge. <https://doi.org/10.4324/9780429452734>

### 11) Session 11: COVID-19 / Mass media and misinformation

-   Input on term papers & RQ

-   \@home: write 1-3 possible research questions that you would like to investigate.

Readings:

-   COVID-19, public health and compliance

    -   Imhoff, R., & Lamberty, P. (2020). A Bioweapon or a Hoax? The Link Between Distinct Conspiracy Beliefs About the Coronavirus Disease (COVID-19) Outbreak and Pandemic Behavior. Social Psychological and Personality Science, 11, 1110--1118. <https://doi.org/10.1177/1948550620934692>

    -   Peitz, L., Lalot, F., Douglas, K. M., Sutton, R., & Abrams, D. (2021). COVID-19 conspiracy theories and compliance with governmental restrictions: The mediating roles of anger, anxiety, and hope. Journal of Pacific Rim Psychology, 15, 18344909211046650. <https://doi.org/10.1177/18344909211046646>

-   Mass media and online misinformation

    -   Bronner, G. (2015). Why are conspiracy theories doing so well? The case of Charlie Hebdo. Diogenes, 62, 8--16. <https://doi.org/10.1177/0392192120924532>

    -   Rooke, M. (2021). Alternative media framing of COVID-19 risks. Current Sociology, 69(4), 584--602. <https://doi.org/10.1177/00113921211006115>

## Research questions and seminar papers / essays

In this last block of sessions, students will work individually and collectively towards their seminar papers or final essays.

#### 12) Session 12: Research questions

-   Students work in groups on their research questions. Then each groups briefly presents the research questions to the others for discussion.

-   Students can use the remaining time to work on abstracts.

-   \@home work on abstract and introduction

#### 13) Session 13: Term paper writing session

-   Peer review of abstracts.

-   Time for questions.

{{< pagebreak >}}

# Additional Information

## Blackboard

It is important to familiarize yourself with Blackboard (<https://lms.fu-berlin.de>), which is the central e-learning platform at FU. Here, you can find all relevant information, announcements, make submissions and contact your colleagues and myself.

## Webex

You may also want to familiarize yourself with the video conference platform Webex, which is the main platform used by FU. You can use it for office hours and to coordinate group work.

-   Information on how to use Webex can be found [here](https://help.webex.com/en-us/8bzter/Cisco-Webex-Meetings-Video-Tutorials).

-   You can download and set-up Webex following the instructions [here](https://portal.zedat.fu-berlin.de/services/index.php?w=1).

## VPN

You might also require to access other resources of Freie Universität that can only be accessed through its Virtual Private Server (VPN) when not on campus. This most importantly includes **access to the course literature**! Information on how to use this service can be found at <https://www.zedat.fu-berlin.de/VPN>.

## Study Guide

The [Study Guide](https://wikis.fu-berlin.de/display/ifs/MA+Sociology+-+European+Societies%3A+Study+Guide) contains important information on all aspects of your studies and particularly on the standards of scientific work that also apply to all submissions in this course.

## Literature

You should be able to access all course readings in one of three ways:

-   Log in to eduroam or the VPN network and use the DOIs of the papers to find and download them.

-   Within eduroam or the VPN network you can use the [PRIMO library catalog](https://fu-berlin.primo.exlibrisgroup.com/discovery/search?vid=49KOBV_FUB:FUB&sortby=rank&lang=de) to access digital versions of the literature.

-   In rare cases in which books are not accessible online, I will provide PDF copies in due time.
