---
title: "Course Introduction"
subtitle: "30228 - Sociology of conspiracy theories"
author: "Philipp Wunderlich"
date: "summer-term 2023"
format:
  revealjs:
    scrollable: true
    preview-links: true
editor: visual
embed-resources: true
slide-level: 3
---

# Introduction

::: notes
-   ask students to introduce themselves!

    -   name

    -   study program / background

    -   interest in the topic
:::

. . .

1.  Introduction to the topic.

2.  Learning goals

3.  Syllabus

4.  Requirements

5.  Technicalities

# This seminar

## Preconceptions

-   What is a conspiracy theory? How would you define the term?

-   Think of one or two examples of conspiracy theories. Why do you think people believe in them?

## Learning goals

-   Explore the research field of emotional stratification.

    -   How does social structure affect emotions?

    -   How do emotions reproduce social structure?

-   *Focus on writing*: How to author papers and provide helpful feedback.

# Requirements

-   Regular participation

-   Active participation

    -   Mandatory reading and reading responses

    -   Writing tasks (RQ, first draft)

-   Grade (Seminar paper / oral exam)

## Regular participation

-   You may miss up to 2 sessions without a doctor's note.

-   I will not control your presence regularly, but:

-   You have to attend regularly, to be able to fulfill active participation

## Active participation

-   Reading responses have to be uploaded each Sunday (end of day).

    -   Miss no more than 2.

-   Submission of research question (31.5.2023)

-   Submission of first draft (750-1500 words, 5.7.2023)

## Module exam

-   Either seminar paper or oral exam.

    -   Seminar paper recommended in this writing-focused course.

    -   Oral exam: Your term paper draft will serve as the basis of the oral exam.

-   Seminar papers will be developed throughout the course

-   Submit final paper until September 30st. (\>3.000 words)

# Course plan

## Syllabus

[Link](https://philwunderlich.github.io/sociology_of_conspiracy_theories_s2023/syllabus.html)

{{< include ../_session_plan.qmd >}}

# Technicalities

## Blackboard

-   Blackboard

    -   Session readings

    -   Upload of reading responses

    -   Submission of research questions, first drafts, and final papers

-   [POLSOZ_V\_30228_23S](https://fu-berlin.blackboard.com/webapps/blackboard/execute/courseMain?course_id=_182833_1 "Sociology of Conspiracy Theories POLSOZ_V_30228_23S")

    -   self-enrollment is enabled.

    -   external students need to register as [auditors](https://www.fu-berlin.de/en/studium/studienorganisation/immatrikulation/weitere-angebote/nebenhoerer/index.html)

## Literature

-   You should be able to access all course readings in one of three ways:

    -   Log in to eduroam or the [VPN network](https://www.zedat.fu-berlin.de/VPN "vpn info") and use the DOIs of the papers to find and download them.

    -   Within eduroam or the VPN network you can use the [PRIMO library catalog](https://fu-berlin.primo.exlibrisgroup.com/discovery/search?vid=49KOBV_FUB:FUB&sortby=rank&lang=de) to access digital versions of the literature.

    -   In rare cases in which books are not accessible online, I will provide copies in due time.

# Questions?

## Blackboard self-enrollment

```{r}
#| echo: false
#| message: false
library(qrcode)
plot(qr_code('https://fu-berlin.blackboard.com/webapps/blackboard/execute/courseMain?course_id=_182833_1'))
```

Or search for the course ID: [POLSOZ_V\_30228_23S](https://fu-berlin.blackboard.com/webapps/blackboard/execute/courseMain?course_id=_182833_1 "Sociology of Conspiracy Theories POLSOZ_V_30228_23S")
