on:
  workflow_dispatch

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "render quarto"
        uses: pommevilla/quarto-render@render@v2

