on:
  workflow_dispatch

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      - name: "render quarto"
        uses: quarto-dev/quarto-actions/render@v2

