on:
  workflow_dispatch

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
        
      - name: "install R"
        uses: r-lib/actions/setup-r@v2
        with: 
          r-version: '4.2.0' # The R version to download (if necessary) and use.        
        
      - name: "Set up Quarto"
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE
          
      - name: "render quarto"
        uses: quarto-dev/quarto-actions/render@v2

