name: quarto

on:
  workflow_dispatch:

jobs:
  quarto-linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install libcurl4-openssl-dev
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      - name: quarto setup
        uses: quarto-dev/quarto-actions/setup@v2
        with: 
          tinytex: true
      - name: quarto render
        uses: quarto-dev/quarto-actions/render@v2
